sudo: required
language: node_js
node_js:
  - 'lts/*' # use latest lts nodejs version
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - $HOME/.npm
    - node_modules

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"
  - npm install -g neon-cli

script:
  - npm run coverage # jest test with coverage flag does coverage too
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
